name: Test and Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        working-directory: ./
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Run lint
        run: yarn lint

